/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Javier
 */
public class MediEvil extends javax.swing.JFrame {

    /**
     * Creates new form MediEvil
     */
    public MediEvil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public Tablero tab;
    public Cronometro cronometro;
    public boolean tablerocreado=false;
    public boolean vidasJug1Creado=false;
    public boolean vidasJug2Creado=false;
    public static String botonPulsado;
    public Vida vidasJug1, vidasJug2;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mosJug1 = new javax.swing.JTextField();
        mosJug2 = new javax.swing.JTextField();
        mosPer1_1 = new javax.swing.JTextField();
        mosPer2_1 = new javax.swing.JTextField();
        mosPer3_1 = new javax.swing.JTextField();
        mosPer1_2 = new javax.swing.JTextField();
        mosPer2_2 = new javax.swing.JTextField();
        mosPer3_2 = new javax.swing.JTextField();
        panelVidasJug1 = new javax.swing.JPanel();
        labelJug1 = new javax.swing.JLabel();
        panelVidasJug2 = new javax.swing.JPanel();
        labelJug2 = new javax.swing.JLabel();
        labelVidasJug1 = new javax.swing.JLabel();
        labelVidasJug2 = new javax.swing.JLabel();
        labelPerJug1 = new javax.swing.JLabel();
        labelPerJug2 = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        labelCronometro = new javax.swing.JLabel();
        bTirar = new javax.swing.JButton();
        bIzquierda = new javax.swing.JButton();
        bAbajo = new javax.swing.JButton();
        bArriba = new javax.swing.JButton();
        bDerecha = new javax.swing.JButton();
        labelMostrarAcc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        mov = new javax.swing.JTextField();
        labelFondo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelDado = new javax.swing.JLabel();
        labelMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        mosJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mosJug1ActionPerformed(evt);
            }
        });
        getContentPane().add(mosJug1);
        mosJug1.setBounds(800, 120, 120, 20);
        mosJug1.setEnabled(false);
        getContentPane().add(mosJug2);
        mosJug2.setBounds(800, 290, 120, 20);
        mosJug2.setEnabled(false);

        mosPer1_1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mosPer1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mosPer1_1ActionPerformed(evt);
            }
        });
        getContentPane().add(mosPer1_1);
        mosPer1_1.setBounds(950, 160, 80, 20);
        mosPer1_1.setEnabled(false);

        mosPer2_1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(mosPer2_1);
        mosPer2_1.setBounds(950, 200, 80, 20);
        mosPer2_1.setEnabled(false);

        mosPer3_1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(mosPer3_1);
        mosPer3_1.setBounds(950, 240, 80, 20);
        mosPer3_1.setEnabled(false);

        mosPer1_2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(mosPer1_2);
        mosPer1_2.setBounds(950, 330, 80, 20);
        mosPer1_2.setEnabled(false);

        mosPer2_2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(mosPer2_2);
        mosPer2_2.setBounds(950, 370, 80, 20);
        mosPer2_2.setEnabled(false);

        mosPer3_2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(mosPer3_2);
        mosPer3_2.setBounds(950, 410, 80, 20);
        mosPer3_2.setEnabled(false);
        getContentPane().add(panelVidasJug1);
        panelVidasJug1.setBounds(810, 160, 100, 100);

        labelJug1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelJug1.setForeground(new java.awt.Color(255, 255, 255));
        labelJug1.setText("JUGADOR 1:");
        getContentPane().add(labelJug1);
        labelJug1.setBounds(700, 120, 90, 20);
        getContentPane().add(panelVidasJug2);
        panelVidasJug2.setBounds(810, 330, 100, 100);

        labelJug2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelJug2.setForeground(new java.awt.Color(255, 255, 255));
        labelJug2.setText("JUGADOR 2:");
        getContentPane().add(labelJug2);
        labelJug2.setBounds(704, 290, 86, 20);

        labelVidasJug1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVidasJug1.setForeground(new java.awt.Color(255, 255, 255));
        labelVidasJug1.setText("VIDAS");
        getContentPane().add(labelVidasJug1);
        labelVidasJug1.setBounds(720, 200, 50, 20);

        labelVidasJug2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelVidasJug2.setForeground(new java.awt.Color(255, 255, 255));
        labelVidasJug2.setText("VIDAS");
        getContentPane().add(labelVidasJug2);
        labelVidasJug2.setBounds(720, 380, 50, 17);

        labelPerJug1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPerJug1.setForeground(new java.awt.Color(255, 255, 255));
        labelPerJug1.setText("PERSONAJES");
        getContentPane().add(labelPerJug1);
        labelPerJug1.setBounds(940, 120, 100, 20);

        labelPerJug2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPerJug2.setForeground(new java.awt.Color(255, 255, 255));
        labelPerJug2.setText("PERSONAJES");
        getContentPane().add(labelPerJug2);
        labelPerJug2.setBounds(940, 290, 94, 20);

        labelTiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTiempo.setForeground(new java.awt.Color(255, 255, 255));
        labelTiempo.setText("TIEMPO");
        getContentPane().add(labelTiempo);
        labelTiempo.setBounds(710, 60, 57, 20);

        labelCronometro.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelCronometro.setForeground(new java.awt.Color(255, 255, 255));
        labelCronometro.setText("00:00");
        getContentPane().add(labelCronometro);
        labelCronometro.setBounds(820, 50, 60, 40);

        bTirar.setBackground(new java.awt.Color(0, 153, 153));
        bTirar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bTirar.setForeground(new java.awt.Color(255, 255, 255));
        bTirar.setText("TIRAR");
        bTirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTirarActionPerformed(evt);
            }
        });
        getContentPane().add(bTirar);
        bTirar.setBounds(950, 550, 80, 25);

        bIzquierda.setBackground(new java.awt.Color(255, 255, 255));
        bIzquierda.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        bIzquierda.setForeground(new java.awt.Color(255, 255, 255));
        bIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaIzquierda.jpg"))); // NOI18N
        bIzquierda.setText("iz");
        bIzquierda.setPreferredSize(new java.awt.Dimension(55, 35));
        bIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIzquierdaActionPerformed(evt);
            }
        });
        getContentPane().add(bIzquierda);
        bIzquierda.setBounds(770, 550, 30, 30);

        bAbajo.setBackground(new java.awt.Color(255, 255, 255));
        bAbajo.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        bAbajo.setForeground(new java.awt.Color(255, 255, 255));
        bAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaAbajo.jpg"))); // NOI18N
        bAbajo.setText("ab");
        bAbajo.setPreferredSize(new java.awt.Dimension(55, 35));
        bAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbajoActionPerformed(evt);
            }
        });
        getContentPane().add(bAbajo);
        bAbajo.setBounds(810, 550, 30, 30);

        bArriba.setBackground(new java.awt.Color(255, 255, 255));
        bArriba.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        bArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaArriba.jpg"))); // NOI18N
        bArriba.setText("ar");
        bArriba.setPreferredSize(new java.awt.Dimension(55, 35));
        bArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bArribaActionPerformed(evt);
            }
        });
        getContentPane().add(bArriba);
        bArriba.setBounds(810, 510, 30, 30);

        bDerecha.setBackground(new java.awt.Color(255, 255, 255));
        bDerecha.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        bDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flechaDerecha.jpg"))); // NOI18N
        bDerecha.setText("de");
        bDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDerechaActionPerformed(evt);
            }
        });
        getContentPane().add(bDerecha);
        bDerecha.setBounds(850, 550, 30, 30);

        labelMostrarAcc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMostrarAcc.setForeground(new java.awt.Color(255, 255, 255));
        labelMostrarAcc.setText("Turno jugador 1");
        getContentPane().add(labelMostrarAcc);
        labelMostrarAcc.setBounds(710, 470, 120, 20);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(890, 60, 150, 25);

        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        fondo.setOpaque(false);
        fondo.setPreferredSize(new java.awt.Dimension(800, 800));
        fondo.setLayout(null);
        getContentPane().add(fondo);
        fondo.setBounds(70, 20, 550, 550);

        mov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movActionPerformed(evt);
            }
        });
        getContentPane().add(mov);
        mov.setBounds(850, 450, 60, 20);

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N
        getContentPane().add(labelFondo);
        labelFondo.setBounds(0, 0, 690, 610);

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VER RECORDS");
        getContentPane().add(jButton2);
        jButton2.setBounds(890, 20, 150, 25);

        panelDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dado_1.png"))); // NOI18N
        panelDado.setText("jLabel1");
        panelDado.setPreferredSize(new java.awt.Dimension(150, 150));
        getContentPane().add(panelDado);
        panelDado.setBounds(950, 450, 80, 80);

        labelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.jpg"))); // NOI18N
        labelMenu.setPreferredSize(new java.awt.Dimension(1090, 833));
        getContentPane().add(labelMenu);
        labelMenu.setBounds(690, -40, 360, 688);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mosJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mosJug1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mosJug1ActionPerformed

    private void mosPer1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mosPer1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mosPer1_1ActionPerformed

    private void bAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbajoActionPerformed
        // TODO add your handling code here:
        botonPulsado=evt.getActionCommand();
        if(!tablerocreado){
            System.out.println("Tablero no creado");
            return;
        }
        Movimiento movi = new Movimiento(Integer.parseInt(mov.getText()),tab);
        movi.start();
    }//GEN-LAST:event_bAbajoActionPerformed

    private void bArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bArribaActionPerformed
        // TODO add your handling code here:
        botonPulsado=evt.getActionCommand();
        if(!tablerocreado){
            System.out.println("Tablero no creado");
            return;
        }
        Movimiento movi = new Movimiento(Integer.parseInt(mov.getText()),tab);
        movi.start();
    }//GEN-LAST:event_bArribaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fondo.removeAll();
        fondo.repaint();
        tab=new Tablero(tab.tam,fondo);
        tablerocreado=true;
        
        panelVidasJug1.removeAll();
        panelVidasJug1.repaint();
        vidasJug1=new Vida(vidasJug1.tam,panelVidasJug1);
        vidasJug1Creado=true;
        
        panelVidasJug2.removeAll();
        panelVidasJug2.repaint();
        vidasJug2=new Vida(vidasJug2.tam,panelVidasJug2);
        vidasJug2Creado=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDerechaActionPerformed
        // TODO add your handling code here:
        botonPulsado=evt.getActionCommand();
        if(!tablerocreado){
            System.out.println("Tablero no creado");
            return;
        }
        Movimiento movi = new Movimiento(Integer.parseInt(mov.getText()),tab);
        movi.start();
    }//GEN-LAST:event_bDerechaActionPerformed

    private void bIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIzquierdaActionPerformed
        // TODO add your handling code here:
        botonPulsado=evt.getActionCommand();
        if(!tablerocreado){
            System.out.println("Tablero no creado");
            return;
        }
        Movimiento movi = new Movimiento(Integer.parseInt(mov.getText()),tab);
        movi.start();
    }//GEN-LAST:event_bIzquierdaActionPerformed

    private void movActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movActionPerformed

    private void bTirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTirarActionPerformed

        numMovimientos();

        // TODO add your handling code here:
    }//GEN-LAST:event_bTirarActionPerformed

   
    public int numMovimientos(){
        
        int numero= (int)(Math.random()*6+1);
        
        switch(numero){
            
            case 1:
                panelDado.setIcon(new ImageIcon(getClass().getResource("/images/dado_1.png")));
                break;
                
            case 2:
                 panelDado.setIcon(new ImageIcon(getClass().getResource("/images/dado_2.png")));
                break;
                
            case 3:
                 panelDado.setIcon(new ImageIcon(getClass().getResource("/images/dado_3.png")));
                break;
                
            case 4:
                 panelDado.setIcon(new ImageIcon(getClass().getResource("/images/dado_4.png")));
                break;
                
            case 5:
                 panelDado.setIcon(new ImageIcon(getClass().getResource("/images/dado_5.png")));
                break;
                
            case 6:
                 panelDado.setIcon(new ImageIcon(getClass().getResource("/images/dado_6.png")));
                break;
                
            
            
        }
        
        
        return numero;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediEvil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediEvil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediEvil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediEvil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediEvil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbajo;
    private javax.swing.JButton bArriba;
    private javax.swing.JButton bDerecha;
    private javax.swing.JButton bIzquierda;
    private javax.swing.JButton bTirar;
    public javax.swing.JPanel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel labelCronometro;
    public static javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelJug1;
    private javax.swing.JLabel labelJug2;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelMostrarAcc;
    private javax.swing.JLabel labelPerJug1;
    private javax.swing.JLabel labelPerJug2;
    private javax.swing.JLabel labelTiempo;
    private javax.swing.JLabel labelVidasJug1;
    private javax.swing.JLabel labelVidasJug2;
    private javax.swing.JTextField mosJug1;
    private javax.swing.JTextField mosJug2;
    public javax.swing.JTextField mosPer1_1;
    public javax.swing.JTextField mosPer1_2;
    public javax.swing.JTextField mosPer2_1;
    public javax.swing.JTextField mosPer2_2;
    public javax.swing.JTextField mosPer3_1;
    public javax.swing.JTextField mosPer3_2;
    private javax.swing.JTextField mov;
    public javax.swing.JLabel panelDado;
    private javax.swing.JPanel panelVidasJug1;
    private javax.swing.JPanel panelVidasJug2;
    // End of variables declaration//GEN-END:variables
}
