/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1;

import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class NuevoJuego extends javax.swing.JFrame {

    /**
     * Creates new form NuevoJuego
     */
    public NuevoJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public Jugador jugador1, jugador2;
    public Tablero tab;
    public Cronometro cronometro;
    public MediEvil mediEvil;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelJug1 = new javax.swing.JLabel();
        nomJugador1 = new javax.swing.JTextField();
        labelJug2 = new javax.swing.JLabel();
        nomJugador2 = new javax.swing.JTextField();
        labelPersonajes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        spinnerMago1 = new javax.swing.JSpinner();
        spinnerPrincesa1 = new javax.swing.JSpinner();
        spinnerGuerrero1 = new javax.swing.JSpinner();
        spinnerMago2 = new javax.swing.JSpinner();
        spinnerPrincesa2 = new javax.swing.JSpinner();
        spinnerGuerrero2 = new javax.swing.JSpinner();
        spinnerCronometro = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        dimensionesTab = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        labelJug1.setBackground(new java.awt.Color(255, 255, 255));
        labelJug1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelJug1.setForeground(new java.awt.Color(255, 255, 255));
        labelJug1.setText("NOMBRE JUGADOR 1:");
        getContentPane().add(labelJug1);
        labelJug1.setBounds(50, 30, 160, 17);
        getContentPane().add(nomJugador1);
        nomJugador1.setBounds(40, 70, 170, 20);

        labelJug2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelJug2.setForeground(new java.awt.Color(255, 255, 255));
        labelJug2.setText("NOMBRE JUGADOR 2:");
        getContentPane().add(labelJug2);
        labelJug2.setBounds(360, 30, 160, 17);

        nomJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomJugador2ActionPerformed(evt);
            }
        });
        getContentPane().add(nomJugador2);
        nomJugador2.setBounds(349, 70, 180, 20);

        labelPersonajes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPersonajes.setForeground(new java.awt.Color(255, 255, 255));
        labelPersonajes.setText("ORDEN DE LOS PERSONAJES");
        getContentPane().add(labelPersonajes);
        labelPersonajes.setBounds(40, 110, 210, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MAGO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 150, 60, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRINCESA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 190, 80, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GUERRERO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 230, 84, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MAGO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 150, 50, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRINCESA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 190, 90, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GUERRERO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 230, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SELECCIONE EL TIEMPO DEL JUEGO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 290, 270, 17);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIAR JUEGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 330, 150, 25);

        spinnerMago1.setModel(new javax.swing.SpinnerNumberModel(1, null, 3, 1));
        getContentPane().add(spinnerMago1);
        spinnerMago1.setBounds(160, 150, 50, 20);

        spinnerPrincesa1.setModel(new javax.swing.SpinnerNumberModel(1, null, 3, 1));
        getContentPane().add(spinnerPrincesa1);
        spinnerPrincesa1.setBounds(160, 190, 50, 20);

        spinnerGuerrero1.setModel(new javax.swing.SpinnerNumberModel(1, null, 3, 1));
        getContentPane().add(spinnerGuerrero1);
        spinnerGuerrero1.setBounds(160, 230, 50, 20);

        spinnerMago2.setModel(new javax.swing.SpinnerNumberModel(1, null, 3, 1));
        getContentPane().add(spinnerMago2);
        spinnerMago2.setBounds(409, 150, 50, 20);

        spinnerPrincesa2.setModel(new javax.swing.SpinnerNumberModel(1, null, 3, 1));
        getContentPane().add(spinnerPrincesa2);
        spinnerPrincesa2.setBounds(410, 190, 50, 20);

        spinnerGuerrero2.setModel(new javax.swing.SpinnerNumberModel(1, null, 3, 1));
        getContentPane().add(spinnerGuerrero2);
        spinnerGuerrero2.setBounds(410, 230, 50, 20);

        spinnerCronometro.setModel(new javax.swing.SpinnerNumberModel(1, null, 10, 1));
        getContentPane().add(spinnerCronometro);
        spinnerCronometro.setBounds(330, 290, 50, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DIMENSIONES DEL TABLERO:(8 A 18)");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 340, 270, 17);

        dimensionesTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimensionesTabActionPerformed(evt);
            }
        });
        getContentPane().add(dimensionesTab);
        dimensionesTab.setBounds(330, 340, 50, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomJugador2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jugador1=new Jugador();
        jugador2=new Jugador();
        jugador1.setNombre(nomJugador1.getText());
        jugador2.setNombre(nomJugador2.getText());
        
        //jugador1.mago.turno=(int) spinnerMago1.getModel().getValue();
        cronometro=new Cronometro();
        if((parseInt(dimensionesTab.getText())<8) || (parseInt(dimensionesTab.getText())>18)){
            JOptionPane.showMessageDialog(null, "Error el tamanio del tablero esta afuera de los limites posibles");
        }
        else if((spinnerPrincesa1.getValue()==spinnerMago1.getValue()) || (spinnerPrincesa1.getValue()==spinnerGuerrero1.getValue())){
            JOptionPane.showMessageDialog(null, "Error los personajes no pueden tener el mismo orden");
        }
        else if((spinnerGuerrero1.getValue()==spinnerMago1.getValue()) || (spinnerGuerrero1.getValue()==spinnerPrincesa1.getValue())){
            JOptionPane.showMessageDialog(null, "Error los personajes no pueden tener el mismo orden");
        }
        else{
            jugador1.mago.turno=(int) spinnerMago1.getValue();
            jugador1.princesa.turno=(int) spinnerPrincesa1.getValue();
            jugador1.guerrero.turno=(int) spinnerGuerrero1.getValue();
            
            jugador2.mago.turno=(int) spinnerMago2.getValue();
            jugador2.princesa.turno=(int) spinnerPrincesa2.getValue();
            jugador2.guerrero.turno=(int) spinnerGuerrero2.getValue();
            
            cronometro.min=(int) spinnerCronometro.getValue();
            
            tab.tam=parseInt(dimensionesTab.getText());
            
            mediEvil=new MediEvil();
            mediEvil.setSize(1066,650);
            mediEvil.setVisible(true);
        }
      
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dimensionesTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimensionesTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dimensionesTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dimensionesTab;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelJug1;
    private javax.swing.JLabel labelJug2;
    private javax.swing.JLabel labelPersonajes;
    private javax.swing.JTextField nomJugador1;
    private javax.swing.JTextField nomJugador2;
    private javax.swing.JSpinner spinnerCronometro;
    private javax.swing.JSpinner spinnerGuerrero1;
    private javax.swing.JSpinner spinnerGuerrero2;
    private javax.swing.JSpinner spinnerMago1;
    private javax.swing.JSpinner spinnerMago2;
    private javax.swing.JSpinner spinnerPrincesa1;
    private javax.swing.JSpinner spinnerPrincesa2;
    // End of variables declaration//GEN-END:variables
}
